//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gives.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Causes_Single_Masking
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Text_First { get; set; }
        public string Text_Second { get; set; }
        public string Image { get; set; }
    }
}
