//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gives.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Causes_Single_Paypal
    {
        public int Id { get; set; }
        public Nullable<int> FirstPrice { get; set; }
        public Nullable<int> SecondPrice { get; set; }
        public Nullable<int> ThirdPrice { get; set; }
    }
}
