//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gives.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Causes_Single_Recent
    {
        public int Id { get; set; }
        public string Image { get; set; }
        public string Title { get; set; }
        public Nullable<decimal> First_Price { get; set; }
        public Nullable<decimal> Second_Price { get; set; }
        public Nullable<decimal> Progress { get; set; }
        public Nullable<int> Donors { get; set; }
        public Nullable<int> Days { get; set; }
        public string Content1 { get; set; }
        public string Content2 { get; set; }
        public string Content3 { get; set; }
    }
}
