//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gives.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentPost
    {
        public int Id { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> Dates { get; set; }
        public Nullable<int> Post_Id { get; set; }
        public Nullable<int> Users_Id { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
    }
}
