//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gives.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GivesEntities : DbContext
    {
        public GivesEntities()
            : base("name=GivesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<About_Masking> About_Masking { get; set; }
        public virtual DbSet<About_Partners> About_Partners { get; set; }
        public virtual DbSet<About_Section> About_Section { get; set; }
        public virtual DbSet<Administrator> Administrators { get; set; }
        public virtual DbSet<Blog_List_Masking> Blog_List_Masking { get; set; }
        public virtual DbSet<Causes_Grid_Masking> Causes_Grid_Masking { get; set; }
        public virtual DbSet<Causes_Grid_Recent> Causes_Grid_Recent { get; set; }
        public virtual DbSet<Causes_List_Recent> Causes_List_Recent { get; set; }
        public virtual DbSet<Causes_Single_Cards> Causes_Single_Cards { get; set; }
        public virtual DbSet<Causes_Single_Masking> Causes_Single_Masking { get; set; }
        public virtual DbSet<Causes_Single_Paypal> Causes_Single_Paypal { get; set; }
        public virtual DbSet<Causes_Single_PayTitle> Causes_Single_PayTitle { get; set; }
        public virtual DbSet<Causes_Single_Recent> Causes_Single_Recent { get; set; }
        public virtual DbSet<Contact_Map> Contact_Map { get; set; }
        public virtual DbSet<Contact_Masking> Contact_Masking { get; set; }
        public virtual DbSet<Contact_Message> Contact_Message { get; set; }
        public virtual DbSet<Footer> Footers { get; set; }
        public virtual DbSet<Gallery_Masking> Gallery_Masking { get; set; }
        public virtual DbSet<Home_Cause> Home_Cause { get; set; }
        public virtual DbSet<Home_Gallery> Home_Gallery { get; set; }
        public virtual DbSet<Home_Need> Home_Need { get; set; }
        public virtual DbSet<Home_Recent> Home_Recent { get; set; }
        public virtual DbSet<Home_Volunteer> Home_Volunteer { get; set; }
        public virtual DbSet<PayPal_Donate> PayPal_Donate { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<Post_To_Tag> Post_To_Tag { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Visa_Master_Donate> Visa_Master_Donate { get; set; }
        public virtual DbSet<Home_Slider> Home_Slider { get; set; }
        public virtual DbSet<Home_Work_Us> Home_Work_Us { get; set; }
        public virtual DbSet<Feature> Features { get; set; }
        public virtual DbSet<Causes_List_Masking> Causes_List_Masking { get; set; }
        public virtual DbSet<Gallery_Images> Gallery_Images { get; set; }
        public virtual DbSet<Contact_Adress> Contact_Adress { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<News_To_Category> News_To_Category { get; set; }
        public virtual DbSet<Become_Volunteer> Become_Volunteer { get; set; }
        public virtual DbSet<User_Messages> User_Messages { get; set; }
        public virtual DbSet<Blog_Single_Masking> Blog_Single_Masking { get; set; }
        public virtual DbSet<CommentNew> CommentNews { get; set; }
        public virtual DbSet<CommentPost> CommentPosts { get; set; }
    }
}
