//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gives.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Footer
    {
        public int Id { get; set; }
        public string Twitter { get; set; }
        public string Google { get; set; }
        public string Facebook { get; set; }
        public string LInkedin { get; set; }
        public string Scype { get; set; }
    }
}
