//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gives.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Home_Volunteer
    {
        public int Id { get; set; }
        public string Title1 { get; set; }
        public string Title2 { get; set; }
        public string Amount { get; set; }
        public string Fullname { get; set; }
        public string Content { get; set; }
        public string Image { get; set; }
        public string Twitter { get; set; }
        public string Facebook { get; set; }
        public string Youtube { get; set; }
        public string Information { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<byte> Status2 { get; set; }
        public int Status3 { get; set; }
    }
}
